version: '3'
services:
  web:
    restart: unless-stopped
    build: ./deployment
    command: ./deployment/start.sh
    ports:
        - "80:80"
        - "5000:5000"
    volumes:
        - .:/app
        - ../web_hrbonus/dist:/frontend
        - ./deployment/nginx.conf:/etc/nginx/nginx.conf

